packages:
  - 'apps/*'
  - 'packages/*'

catalog:
  '@tanstack/react-query': ^5.76.1
  '@tanstack/react-router': ^1.120.3
  '@tanstack/router-devtools': ^1.120.3
  '@tanstack/router-plugin': ^1.120.3
  '@trpc/client': ^11.1.2
  '@trpc/react-query': ^11.1.2
  '@trpc/server': ^11.1.2
  tailwindcss: ^4.1.6
  '@tailwindcss/vite': ^4.1.6
  '@hookform/resolvers': '^5.0.1'
  zod: ^3.24.4
  react: ^19.1.0
  react-dom: ^19.1.0
  'react-hook-form': '7.56.3'
  '@types/react': ^19.1.4
  '@types/react-dom': ^19.1.5
  axios: ^1.9.0
