export const mailTemplate = [
  'REGISTER',
  'RESET_PASSWORD',
  'CONTACT',
  'CREATE_RESERVATION',
  'REMIND_RESERVATION',
  'DELETE_RESERVATION',
  'DELETE_RESERVATION_STUDENT',
  'PAYMENT_SUBSCRIPTION_STUDENT',
  'PAYMENT_LESSON_PACK',
  'CANCEL_SUBSCRIPTION_STUDENT',
  'CREATE_RESERVATION_STUDENT_V2',
  'PLATFORM_OPENING',
] as const

export type MailTemplate = (typeof mailTemplate)[number]

export const MailTemplateEnum: Record<MailTemplate, number> = {
  REGISTER: 1,
  RESET_PASSWORD: 3,
  CONTACT: 4,
  CREATE_RESERVATION: 5,
  REMIND_RESERVATION: 6,
  DELETE_RESERVATION: 7,
  DELETE_RESERVATION_STUDENT: 16,
  PAYMENT_SUBSCRIPTION_STUDENT: 17,
  PAYMENT_LESSON_PACK: 19,
  CANCEL_SUBSCRIPTION_STUDENT: 18,
  CREATE_RESERVATION_STUDENT_V2: 21,
  PLATFORM_OPENING: 22,
}
